pipeline {
    agent any

    environment {
        MAVEN_HOME = tool 'Maven'
        PATH = "${MAVEN_HOME}/bin:${env.PATH}"
    }

    stages {

        stage('Compile Stage') {
            steps {
                sh 'mvn clean compile'
            }
        }

        stage('Testing Stage') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Dependency Check') {
            steps {
                withCredentials([string(credentialsId: 'nvd-api-key', variable: 'NVD_KEY')]) {
                    sh '''
                        /opt/dependency-check/bin/dependency-check.sh \
                            --scan ./ \
                            --exclude "**/node_modules/**" \
                            --format XML \
                            --format HTML \
                            --out ./dependency-check-report \
                            --data /opt/dependency-check/data \
                            --nvdApiKey $NVD_KEY \
                            --prettyPrint
                    ''' //--scan <target-path> 
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('Sonar-Scan') {
                    sh '''
                        mvn sonar:sonar \
                            -Dsonar.projectKey=openobserve \ 
                            -Dsonar.projectName="Open Observe" \
                            -Dsonar.sources=web/src \
                            -Dsonar.javascript.node.maxspace=4096 \
                            -Dsonar.exclusions=**/node_modules/**,**/*.test.*,**/*.spec.*,**/test_logs.json,**/dist/**,**/build/**,**/__tests__/**,**/*.min.js,**/*.d.ts,**/coverage/**
                    ''' //source should be path to scan 
                }
            }
        }

        stage('Package Stage') {
            steps {
                sh 'mvn package'
            }
        }

    }

    post {
        always {
            dependencyCheckPublisher pattern: 'dependency-check-report/dependency-check-report.xml'
            archiveArtifacts artifacts: 'dependency-check-report/**', fingerprint: true
            echo 'Pipeline finished.'
        }
        success {
            echo '✅ All stages passed successfully!'
        }
        unstable {
            echo '⚠️ Pipeline completed with warnings.'
        }
        failure {
            echo '❌ Pipeline failed. Check the logs above.'
        }
    }
}
